/**
 * Activation Dashboard (BUILD_PROMPT §12). KPI tiles mirroring SBI's scorecard + the dormant→active
 * funnel that TICKS LIVE when a nudge is confirmed on the phone (via the WS stream).
 */
import { motion } from "framer-motion";
import type { ActivationResponse } from "../api/types";
import { Kpi, OpsCard, SectionTitle } from "./widgets";

const MAXW = 100;

export function ActivationView({ data, pulse }: { data: ActivationResponse | null; pulse: number }) {
  if (!data) return <Loading />;
  const max = Math.max(...data.funnel.map((f) => f.count), 1);

  return (
    <div className="flex flex-col gap-8">
      <OpsCard>
        <SectionTitle 
          eyebrow="North-star scorecard" 
          title="Activation & Cross-sell" 
          desc="Monitors the real-time lift in engagement generated by AI nudges, reducing reliance on expensive external customer acquisition channels."
        />
        <div className="grid grid-cols-2 gap-6 md:grid-cols-4">
          {data.kpis.map((k) => (
            <Kpi key={k.key} tile={k} flash={pulse > 0} />
          ))}
        </div>
      </OpsCard>

      <OpsCard>
        <div className="flex flex-col md:flex-row md:items-start justify-between gap-4">
          <div className="flex-1">
            <SectionTitle 
              eyebrow="The 9 crore you already have" 
              title="Dormant → Active pipeline" 
              desc="Tracks the real-time conversion of dormant users into active, revenue-generating users as they confirm AI-surfaced nudges."
            />
          </div>
          <motion.span
            key={pulse}
            initial={{ scale: pulse ? 1.05 : 1, backgroundColor: pulse ? "#34C759" : "rgba(52,199,89,0.15)" }}
            animate={{ scale: 1, backgroundColor: "rgba(52,199,89,0.1)" }}
            transition={{ duration: 0.8 }}
            className="flex h-fit items-center gap-2 rounded-full px-3 py-1.5 text-xs font-bold uppercase tracking-wider text-[#34C759]"
          >
            <span className="h-1.5 w-1.5 animate-pulse rounded-full bg-[#34C759]" />
            Live - {data.confirmed_today} converted
          </motion.span>
        </div>

        <div className="mt-4 flex flex-col gap-4">
          {data.funnel.map((f, i) => {
            const w = (f.count / max) * MAXW;
            const isActive = f.key === "active";
            return (
              <div key={f.key} className="flex items-center gap-6">
                <span className="w-28 shrink-0 text-sm font-medium text-[#8E8E93]">{f.label}</span>
                <div className="relative h-8 flex-1 overflow-hidden rounded-md bg-[#F2F2F7]">
                  <motion.div
                    animate={{ width: `${w}%` }}
                    transition={{ type: "spring", stiffness: 120, damping: 22 }}
                    className={
                      "flex h-full items-center justify-end rounded-md pr-3 " +
                      (isActive
                        ? "bg-[#007AFF]"
                        : i === 1
                        ? "bg-[#D1D1D6]"
                        : "bg-[#007AFF]/60")
                    }
                  >
                    <motion.span
                      key={f.count}
                      initial={{ opacity: 0 }}
                      animate={{ opacity: 1 }}
                      className="font-mono text-sm font-semibold text-white"
                    >
                      {f.count.toLocaleString("en-IN")}
                    </motion.span>
                  </motion.div>
                </div>
              </div>
            );
          })}
        </div>
      </OpsCard>
    </div>
  );
}

function Loading() {
  return <div className="ai-shimmer h-64 rounded-3xl" />;
}
